export const ROUTE_NAMES = {
  homePage: '/',
  aboutPage: 'about',
  blogPage: 'blog',
  eventPage: 'event',
  galleryPage: 'gallery',
  contactPage: 'contact',
  loginPage: 'login',
  notFoundPublic: 'not-found',
  adminPage: 'admin',
  dashboardPage: 'dashboard',
  articlesPage: 'articles',
  eventsPage: 'events',
  tagsPage: 'tags',
  categoriesPage: 'categories',
  usersPage: 'users',
  imagesPage: 'images',
  subscriptionsPage: 'subscriptions',
  settingsPage: 'settings',
  notFoundCms: 'item-not-found',
  newEmailPost: 'new-email-post',
  newUser: 'new-user',
  userDetail: 'user-detail',
}
